import type { Action, Actions, LiveInteraction, StatDeltas } from "@gk/schema";
import { ACTIONS, SKILLS, STYLES } from "./ids";

type Band = "strong" | "adequate" | "weak" | "harmful";
type Consequences = LiveInteraction["consequences"];
type Triggers = LiveInteraction["triggers"];

const bandNames = { strong: "Strong", adequate: "Adequate", weak: "Weak", harmful: "Harmful" };

const redFlags = [
  { id: "blame", label: "Blame", description: "Blames the person or others instead of addressing the issue" },
  { id: "threat", label: "Threat", description: "Threatens the person's job or uses intimidation" },
  {
    id: "discrimination",
    label: "Discrimination",
    description: "Treats the person unfairly because of who they are",
  },
  {
    id: "policy-breach",
    label: "Policy breach",
    description: "Asks for or promises something that breaks policy",
  },
];

const noTriggers: Triggers = { strong: [], adequate: [], weak: [], harmful: [] };

/** Default band consequences for a conversation with one person (derived, tuned by the balance gate). */
const oneToOne = (harmfulTeamMorale = -2): Consequences => ({
  strong: { target: { morale: 6, trust: 8, result: 4 }, bystanders: [], sponsor: 0 },
  adequate: { target: { morale: 2, trust: 2 }, bystanders: [], sponsor: 0 },
  weak: { target: { morale: -3, trust: -4 }, bystanders: [], sponsor: 0 },
  harmful: {
    target: { morale: -8, trust: -12 },
    bystanders: [{ selector: { kind: "team" }, deltas: { morale: harmfulTeamMorale } }],
    sponsor: 0,
  },
});

const teamWide = (
  strong: StatDeltas,
  adequate: StatDeltas,
  weak: StatDeltas,
  harmful: StatDeltas,
): Consequences => ({
  strong: { target: {}, bystanders: [{ selector: { kind: "team" }, deltas: strong }], sponsor: 0 },
  adequate: { target: {}, bystanders: [{ selector: { kind: "team" }, deltas: adequate }], sponsor: 0 },
  weak: { target: {}, bystanders: [{ selector: { kind: "team" }, deltas: weak }], sponsor: 0 },
  harmful: { target: {}, bystanders: [{ selector: { kind: "team" }, deltas: harmful }], sponsor: 0 },
});

interface LiveInput {
  format: LiveInteraction["format"];
  minutes: number;
  turns: number;
  evaluatesStyle: boolean;
  goal: string;
  context: string;
  npcBrief: LiveInteraction["npcBrief"];
  skills: string[];
  concernPhrases?: string[];
  consequences: Consequences;
  triggers?: Partial<Record<Band, Triggers[Band]>>;
  opening?: LiveInteraction["opening"];
  optional?: boolean;
  tips?: string[];
  email?: LiveInteraction["email"];
  meeting?: LiveInteraction["meeting"];
  interview?: LiveInteraction["interview"];
}

function live(i: LiveInput): LiveInteraction {
  return {
    optional: i.optional ?? false,
    format: i.format,
    inputModes: "both",
    timeLimit: { minutes: i.minutes, stop: "soft" },
    turnLimit: i.turns,
    evaluatesStyle: i.evaluatesStyle,
    participantBrief: { goal: i.goal, context: i.context, showNpcCard: true },
    npcBrief: i.npcBrief,
    difficulty: "standard",
    opening: i.opening ?? { speaker: "npc" },
    rubric: {
      dimensions: i.skills.map((skillId) => ({ skillId })),
      concernDetection: {
        phrases: i.concernPhrases ?? [
          "what is really going on for you",
          "is anything outside work affecting you",
          "what would help you right now",
        ],
      },
      redFlags,
      aggregation: "median_lower",
    },
    bandNames,
    consequences: i.consequences,
    triggers: { ...noTriggers, ...i.triggers },
    hints: {
      policy: "on_request",
      tips: i.tips ?? ["Ask before you tell: find out what the person needs first."],
    },
    calibrationSet: [],
    ...(i.email ? { email: i.email } : {}),
    ...(i.meeting ? { meeting: i.meeting } : {}),
    ...(i.interview ? { interview: i.interview } : {}),
  };
}

/** A style tagged option (Teardown: options map one to one onto the four styles). */
const styled = (
  id: string,
  label: string,
  styleTag: string,
  match: StatDeltas,
  matchQuote: string,
  mismatch: StatDeltas,
  mismatchQuote: string,
) => ({
  id,
  label,
  description: label,
  styleTag,
  effects: [],
  consequences: { match, mismatch },
  quotes: { match: [matchQuote], mismatch: [mismatchQuote] },
});

const plain = (
  id: string,
  label: string,
  description: string,
  any: StatDeltas,
  quote: string,
  extra: Partial<Action["options"][number]> = {},
) => ({
  id,
  label,
  description,
  effects: [],
  consequences: { any },
  quotes: { any: [quote] },
  ...extra,
});

const MISMATCH: StatDeltas = { morale: -3, result: -4 };
const CHANGE_STYLE = "I'm happy with some of this, but please change your style with me.";

const base = {
  hidden: false,
  cooldownDays: 0,
  eligibility: [] as Action["eligibility"],
  prerequisites: [] as Action["prerequisites"],
  effects: [] as Action["effects"],
  baseConsequences: { target: {} },
  unlock: { kind: "always" as const },
  countsTowardLiveCap: true,
};

// TODO(decision): D-09 modes follow the Design doc action table. D-12 Give feedback, Meet the team and Hire
// have no observed data; they use the Design doc live formats (chat, team meeting, interview).
const catalogue: Action[] = [
  {
    ...base,
    id: ACTIONS.meetTeam,
    name: "Meet the team",
    icon: "team",
    description: "Hold a team meeting to set direction and hear the team.",
    group: "team",
    scope: "team",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 0, maxTargets: 0 },
    options: [],
    interaction: live({
      format: "team_meeting",
      minutes: 7,
      turns: 12,
      evaluatesStyle: false,
      goal: "Run a short team meeting that sets direction and brings quieter people in.",
      context: "The whole team is here. Some are frustrated, some are quiet, and one or two may push back.",
      npcBrief: {
        wants: "To know where the team is heading",
        fears: "More change without a say",
        hides: "Private frustrations with each other",
        willAccept: "A clear agenda and a chance to speak",
      },
      skills: [SKILLS.flexibility, SKILLS.recognition, SKILLS.change],
      consequences: teamWide(
        { morale: 3, trust: 3 },
        { morale: 1, trust: 1 },
        { morale: -1, trust: -2 },
        { morale: -4, trust: -6 },
      ),
      meeting: { attendees: "whole_team", agendaRequired: true, npcToNpc: true },
    }),
  },
  {
    ...base,
    id: ACTIONS.energize,
    name: "Energize the team",
    icon: "energize",
    description: "Lift the team with a lunch or a team building activity.",
    group: "team",
    scope: "team",
    mode: "static",
    dayCost: 1,
    cooldownDays: 10,
    limits: { minTargets: 0, maxTargets: 0 },
    options: [
      plain(
        "team-lunch",
        "Team lunch",
        "A relaxed lunch together",
        {},
        "The team enjoyed it and wants more of this.",
        {
          dayCost: 1,
          effects: [{ kind: "team_delta", deltas: { morale: 2, result: 3 }, excludeUnavailable: true }],
        },
      ),
      plain(
        "team-building",
        "Team building activity",
        "A half day activity away from the desk",
        {},
        "That was a real lift for the team.",
        {
          dayCost: 2,
          effects: [{ kind: "team_delta", deltas: { morale: 4, result: 4 }, excludeUnavailable: true }],
        },
      ),
    ],
    interaction: live({
      optional: true,
      format: "team_meeting",
      minutes: 1,
      turns: 1,
      evaluatesStyle: false,
      goal: "Give a short toast that recognises the team.",
      context: "Optional: a 60 second toast before the activity.",
      npcBrief: {
        wants: "To feel seen as a team",
        fears: "Empty words",
        hides: "Nothing",
        willAccept: "Specific, sincere thanks",
      },
      skills: [SKILLS.recognition, SKILLS.change],
      consequences: teamWide({ morale: 2 }, { morale: 1 }, {}, { morale: -2 }),
      meeting: { attendees: "whole_team", agendaRequired: false, npcToNpc: false },
    }),
  },
  {
    ...base,
    id: ACTIONS.email,
    name: "Send email",
    icon: "email",
    description: "Write to up to 3 people.",
    group: "team",
    scope: "multi_select",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 3 },
    eligibility: [{ kind: "team_members_only" }],
    options: [
      plain(
        "warning-mail",
        "Warning mail",
        "Flag a problem with performance or conduct",
        { morale: -3, result: 2 },
        "Understood. I'll fix it.",
      ),
      plain(
        "congratulatory-mail",
        "Congratulatory mail",
        "Thank people for good work",
        { morale: 9, result: 8 },
        "Thank you. I'll strive even harder.",
      ),
    ],
    interaction: live({
      format: "email",
      minutes: 4,
      turns: 1,
      evaluatesStyle: false,
      goal: "Write an email that does what you intend and is fair to everyone on it.",
      context: "Each recipient will reply. People who were left off may notice.",
      npcBrief: {
        wants: "A clear, specific message",
        fears: "Being singled out unfairly",
        hides: "How they compare themselves with peers",
        willAccept: "Specific praise or specific, fair feedback",
      },
      skills: [SKILLS.feedback, SKILLS.recognition, SKILLS.change],
      consequences: oneToOne(-1),
      email: {
        recipientsAllowed: "team_members",
        cc: true,
        bcc: false,
        attachments: false,
        replyAllReactions: true,
      },
    }),
  },
  {
    ...base,
    id: ACTIONS.swap,
    name: "Swap or reassign roles",
    icon: "swap",
    description: "Move people between stages, then explain the move.",
    group: "team",
    scope: "multi_select",
    mode: "hybrid",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 2 },
    eligibility: [
      { kind: "team_members_only" },
      { kind: "available_only" },
      { kind: "max_per_role", max: 2 },
    ],
    prerequisites: [
      {
        actionId: ACTIONS.assess,
        match: "same_target_and_role",
        penalty: { morale: -5, result: -5 },
        nudge: true,
        missQuote: "You should have assessed me before moving me.",
      },
    ],
    options: [
      plain(
        "swap-two",
        "Swap 2 members",
        "Two people trade stages",
        {},
        "Thanks for explaining. I'll give the new role a go.",
        { effects: [{ kind: "swap_roles" }] },
      ),
      plain(
        "reassign-one",
        "Reassign 1 member",
        "Move one person to a stage with space",
        {},
        "Thanks for explaining. I'll give the new role a go.",
        { effects: [{ kind: "reassign_role" }] },
      ),
    ],
    baseConsequences: { target: {}, rippleTrigger: "moved" },
    interaction: live({
      format: "roleplay_1to1",
      minutes: 3,
      turns: 8,
      evaluatesStyle: false,
      goal: "Explain the move and set clear expectations for the new role.",
      context: "The decision is made. How you explain it shapes how the person takes it.",
      npcBrief: {
        wants: "To understand why",
        fears: "That the move is a demotion",
        hides: "What they really think of the new role",
        willAccept: "A reason, support and clear expectations",
      },
      skills: [SKILLS.feedback, SKILLS.change, SKILLS.difficult],
      consequences: oneToOne(),
    }),
  },
  {
    ...base,
    id: ACTIONS.training,
    name: "Send for training",
    icon: "training",
    description: "Send up to 3 people to training. They are away while it runs.",
    group: "team",
    scope: "multi_select",
    mode: "static",
    dayCost: 2,
    limits: { minTargets: 1, maxTargets: 3 },
    eligibility: [{ kind: "team_members_only" }, { kind: "available_only" }, { kind: "peer_covers_role" }],
    options: [
      plain(
        "workshop",
        "1 week workshop",
        "A full week away; bigger skill gain",
        {},
        "Thanks. I'm not sure I'll use it straight away.",
        {
          dayCost: 2,
          effects: [
            { kind: "make_unavailable", days: 5, status: "training" },
            { kind: "delayed_delta", afterDays: 5, deltas: { skill: 6, morale: 5, result: 3 } },
          ],
        },
      ),
      plain(
        "short-training",
        "3 day training",
        "Three days away; smaller skill gain",
        {},
        "Thanks. Useful refresher.",
        {
          dayCost: 1,
          effects: [
            { kind: "make_unavailable", days: 3, status: "training" },
            { kind: "delayed_delta", afterDays: 3, deltas: { skill: 3, morale: 2, result: 2 } },
          ],
        },
      ),
    ],
  },
  {
    ...base,
    id: ACTIONS.hire,
    name: "Hire member",
    icon: "hire",
    description: "Interview 2 candidates, then choose.",
    group: "team",
    scope: "team",
    mode: "live",
    dayCost: 2,
    limits: { minTargets: 0, maxTargets: 0 },
    eligibility: [{ kind: "team_not_full" }],
    effects: [{ kind: "hire_candidate" }],
    options: [],
    interaction: live({
      format: "interview",
      minutes: 5,
      turns: 10,
      evaluatesStyle: false,
      opening: { speaker: "participant" },
      goal: "Find out who will really perform, with fair and structured questions.",
      context:
        "Two candidates for an open sales associate role. Their true performance shows over the following weeks.",
      npcBrief: {
        wants: "The job",
        fears: "Hard questions about past results",
        hides: "Their true track record",
        willAccept: "A fair process",
      },
      skills: [SKILLS.recognition, SKILLS.results],
      consequences: {
        strong: { target: {}, bystanders: [], sponsor: 5 },
        adequate: { target: {}, bystanders: [], sponsor: 0 },
        weak: { target: {}, bystanders: [], sponsor: -5 },
        harmful: {
          target: {},
          bystanders: [{ selector: { kind: "team" }, deltas: { trust: -3 } }],
          sponsor: -10,
        },
      },
      interview: { candidates: 2, questionBank: true, hiddenTrueProfile: true },
    }),
  },
  {
    ...base,
    id: ACTIONS.fire,
    name: "Fire member",
    icon: "fire",
    description: "Let someone go, then hold the exit conversation.",
    group: "team",
    scope: "individual",
    mode: "hybrid",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }, { kind: "min_left_in_role", min: 1 }],
    effects: [{ kind: "remove_member" }],
    options: [],
    baseConsequences: { target: {}, rippleTrigger: "fired" },
    interaction: live({
      format: "roleplay_1to1",
      minutes: 4,
      turns: 10,
      evaluatesStyle: false,
      goal: "Hold the exit conversation with dignity, clarity and within policy.",
      context: "The decision is final. The rest of the team will hear how it was handled.",
      npcBrief: {
        wants: "Respect and a clear reason",
        fears: "Humiliation",
        hides: "How worried they are about money",
        willAccept: "Honesty and fair treatment",
      },
      skills: [SKILLS.feedback, SKILLS.change, SKILLS.difficult],
      consequences: {
        strong: {
          target: {},
          bystanders: [{ selector: { kind: "team" }, deltas: { trust: 1 } }],
          sponsor: 0,
        },
        adequate: {
          target: {},
          bystanders: [{ selector: { kind: "team" }, deltas: { morale: -1 } }],
          sponsor: 0,
        },
        weak: {
          target: {},
          bystanders: [{ selector: { kind: "team" }, deltas: { morale: -3, trust: -3 } }],
          sponsor: 0,
        },
        harmful: {
          target: {},
          bystanders: [{ selector: { kind: "team" }, deltas: { morale: -5, trust: -8 } }],
          sponsor: -10,
        },
      },
      triggers: { harmful: [{ kind: "follow_up_event", eventId: "hr-escalation", afterDays: 1 }] },
    }),
  },
  {
    ...base,
    id: ACTIONS.faceToFace,
    name: "Meet face to face",
    icon: "meet",
    description: "A one to one conversation with a team member.",
    group: "individual",
    scope: "individual",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }, { kind: "available_only" }],
    options: [
      styled(
        "emotional-support",
        "Energize with emotional support",
        STYLES.guiding,
        { morale: 3, result: 4 },
        "Thanks, that is what I needed.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "own-processes",
        "Follow own processes",
        STYLES.entrusting,
        { morale: 3, result: 4 },
        "Thanks for trusting me with it.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "execution-plan",
        "Detailed execution plan",
        STYLES.directing,
        { morale: 3, result: 4 },
        "Clear. I know exactly what to do now.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "discuss-role",
        "Discuss role and ask feedback",
        STYLES.partnering,
        { morale: 3, result: 4 },
        "Good to talk it through together.",
        MISMATCH,
        CHANGE_STYLE,
      ),
    ],
    interaction: live({
      format: "roleplay_1to1",
      minutes: 5,
      turns: 12,
      evaluatesStyle: true,
      goal: "Find out what this person needs and agree what happens next.",
      context: "Use what you know about them: their stats, remarks and what has happened this week.",
      npcBrief: {
        wants: "To be heard",
        fears: "Being judged on numbers alone",
        hides: "Their hidden concern",
        willAccept: "Concrete support matched to what they need",
      },
      skills: [SKILLS.flexibility, SKILLS.coaching, SKILLS.difficult],
      consequences: {
        strong: { target: { morale: 8, trust: 10, result: 5 }, bystanders: [], sponsor: 0 },
        adequate: { target: { morale: 3, trust: 3 }, bystanders: [], sponsor: 0 },
        weak: { target: { morale: -4, trust: -6 }, bystanders: [], sponsor: 0 },
        harmful: {
          target: { morale: -10, trust: -15 },
          bystanders: [{ selector: { kind: "team" }, deltas: { morale: -2 } }],
          sponsor: 0,
        },
      },
      triggers: {
        strong: [{ kind: "resolve_concern" }, { kind: "log_promise" }],
        adequate: [{ kind: "log_promise" }],
        harmful: [{ kind: "follow_up_event", eventId: "transfer-request", afterDays: 2 }],
      },
    }),
  },
  {
    ...base,
    id: ACTIONS.assess,
    name: "Assess member",
    icon: "assess",
    description: "See how someone would do in another stage.",
    group: "individual",
    scope: "individual",
    mode: "static",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }],
    options: [
      plain(
        "assess-role",
        "Assess for a target role",
        "Reveals Skill, Motivation and Performance in that role",
        {},
        "Here is how I think I would do in that role.",
        { effects: [{ kind: "reveal_role_fit" }] },
      ),
    ],
  },
  {
    ...base,
    id: ACTIONS.reward,
    name: "Reward member",
    icon: "reward",
    description: "Give a bonus, then write the recognition note.",
    group: "individual",
    scope: "individual",
    mode: "hybrid",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }],
    options: [plain("bonus", "Bonus", "A one off bonus", { morale: 4, result: 8 }, "Thanks for the bonus.")],
    baseConsequences: { target: {}, rippleTrigger: "rewarded" },
    interaction: live({
      format: "email",
      minutes: 3,
      turns: 1,
      evaluatesStyle: true,
      goal: "Write a recognition note that is specific, fair and linked to results.",
      context: "Others will hear about this bonus. Think about who else deserved credit.",
      npcBrief: {
        wants: "Specific recognition",
        fears: "That it looks like favouritism",
        hides: "Who helped them",
        willAccept: "Sincere, specific thanks",
      },
      skills: [SKILLS.recognition, SKILLS.feedback],
      consequences: oneToOne(-1),
      email: {
        recipientsAllowed: "one",
        cc: false,
        bcc: false,
        attachments: false,
        replyAllReactions: false,
      },
    }),
  },
  {
    ...base,
    id: ACTIONS.goals,
    name: "Set goals",
    icon: "goals",
    description: "Agree goals in a short written plan, then check in.",
    group: "individual",
    scope: "individual",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }, { kind: "available_only" }],
    options: [
      styled(
        "seek-buy-in",
        "Seek buy-in",
        STYLES.guiding,
        { skill: 3, morale: 4, result: 6 },
        "Happy with the plan. I'll come to you if I need anything.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "ask-focus",
        "Ask focus",
        STYLES.entrusting,
        { skill: 3, morale: 4, result: 6 },
        "Thanks for letting me set the focus.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "tasks-milestones",
        "Send tasks and milestones",
        STYLES.directing,
        { skill: 3, morale: 4, result: 6 },
        "Happy with the plan. I'll come to you if I need anything.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "plan-inputs",
        "Send plan and seek inputs",
        STYLES.partnering,
        { skill: 3, morale: 4, result: 6 },
        "Good plan. Glad you asked for my input.",
        MISMATCH,
        CHANGE_STYLE,
      ),
    ],
    interaction: live({
      format: "written_plan",
      minutes: 3,
      turns: 4,
      evaluatesStyle: true,
      goal: "Agree specific, measurable goals with the right level of involvement for this person.",
      context: "Commitment shapes this person's output next week.",
      npcBrief: {
        wants: "Goals they believe in",
        fears: "Targets with no support",
        hides: "Doubts about what is realistic",
        willAccept: "Specific goals with the support they need",
      },
      skills: [SKILLS.flexibility, SKILLS.goals, SKILLS.results],
      consequences: oneToOne(),
      triggers: { strong: [{ kind: "log_promise" }] },
    }),
  },
  {
    ...base,
    id: ACTIONS.coach,
    name: "Coach member",
    icon: "coach",
    description: "A coaching conversation to build skill.",
    group: "individual",
    scope: "individual",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }, { kind: "available_only" }],
    options: [
      styled(
        "guidance-importance",
        "Guidance and importance",
        STYLES.guiding,
        { skill: 6, morale: 3, result: 7 },
        "That was very useful. I'd like more sessions.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "ask-questions",
        "Ask questions",
        STYLES.entrusting,
        { skill: 6, morale: 3, result: 7 },
        "Good questions. I know what to try next.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "handhold-plan",
        "Handhold with detailed plan",
        STYLES.directing,
        { skill: 6, morale: 3, result: 7 },
        "You are an excellent coach.",
        MISMATCH,
        CHANGE_STYLE,
      ),
      styled(
        "solve-together",
        "Solve collaboratively",
        STYLES.partnering,
        { skill: 6, morale: 3, result: 7 },
        "Working it out together really helped.",
        MISMATCH,
        CHANGE_STYLE,
      ),
    ],
    interaction: live({
      format: "roleplay_1to1",
      minutes: 5,
      turns: 12,
      evaluatesStyle: true,
      goal: "Help this person own a specific next step, using good questions.",
      context: "A coaching structure helps: goal, reality, options, way forward.",
      npcBrief: {
        wants: "To get better at the job",
        fears: "Being told what they already know",
        hides: "Where they are stuck",
        willAccept: "Questions that help them find the answer, plus support",
      },
      skills: [SKILLS.flexibility, SKILLS.coaching, SKILLS.goals],
      consequences: {
        strong: { target: { skill: 4, morale: 4, trust: 6, result: 4 }, bystanders: [], sponsor: 0 },
        adequate: { target: { skill: 2, morale: 2, trust: 2 }, bystanders: [], sponsor: 0 },
        weak: { target: { morale: -2, trust: -3 }, bystanders: [], sponsor: 0 },
        harmful: {
          target: { morale: -8, trust: -12 },
          bystanders: [{ selector: { kind: "team" }, deltas: { morale: -2 } }],
          sponsor: 0,
        },
      },
      triggers: { strong: [{ kind: "log_promise" }] },
    }),
  },
  {
    ...base,
    id: ACTIONS.feedback,
    name: "Give feedback",
    icon: "feedback",
    description: "Give one person feedback on their work.",
    group: "individual",
    scope: "individual",
    mode: "live",
    dayCost: 1,
    limits: { minTargets: 1, maxTargets: 1 },
    eligibility: [{ kind: "team_members_only" }, { kind: "available_only" }],
    options: [],
    baseConsequences: { target: {}, rippleTrigger: "criticised" },
    interaction: live({
      format: "chat",
      minutes: 3,
      turns: 10,
      evaluatesStyle: true,
      goal: "Name the situation, the behaviour and its impact, and agree what changes.",
      context: "Balanced, specific feedback lands. Repeated poor feedback lowers trust.",
      npcBrief: {
        wants: "Fair, specific feedback",
        fears: "Vague criticism",
        hides: "Their side of the story",
        willAccept: "Clear examples and a way forward",
      },
      skills: [SKILLS.flexibility, SKILLS.feedback, SKILLS.recognition, SKILLS.difficult],
      consequences: oneToOne(),
    }),
  },
  {
    ...base,
    id: ACTIONS.reply,
    name: "Reply to NPC messages",
    icon: "chat",
    description: "Answer a message a team member sent you.",
    group: "individual",
    scope: "individual",
    mode: "live",
    dayCost: 0,
    limits: { minTargets: 1, maxTargets: 1 },
    options: [],
    unlock: { kind: "npc_message" },
    countsTowardLiveCap: false,
    interaction: live({
      format: "chat",
      minutes: 3,
      turns: 10,
      evaluatesStyle: true,
      goal: "Respond in a way that fits the situation and the person.",
      context: "Ignoring a message lets it escalate next week.",
      npcBrief: {
        wants: "A timely, human reply",
        fears: "Being ignored",
        hides: "How serious the issue is",
        willAccept: "Acknowledgement and a next step",
      },
      skills: [SKILLS.flexibility, SKILLS.difficult],
      consequences: oneToOne(),
      triggers: { strong: [{ kind: "resolve_concern" }] },
    }),
  },
  {
    ...base,
    id: ACTIONS.briefing,
    name: "Sponsor briefing",
    icon: "briefing",
    description: "Brief the CEO on results and your plan.",
    group: "team",
    scope: "team",
    mode: "live",
    dayCost: 0,
    limits: { minTargets: 0, maxTargets: 0 },
    options: [],
    unlock: { kind: "scheduled", weeks: [4, 8] },
    countsTowardLiveCap: false,
    interaction: live({
      format: "sponsor_briefing",
      minutes: 4,
      turns: 8,
      evaluatesStyle: false,
      opening: { speaker: "participant" },
      goal: "Own the results, be honest about gaps and present a credible plan.",
      context: "Roger Kent will probe. His confidence affects your budget and hires.",
      npcBrief: {
        wants: "Ownership and a credible plan",
        fears: "Excuses",
        hides: "Pressure from the board",
        willAccept: "Honest numbers and clear next steps",
      },
      skills: [SKILLS.goals, SKILLS.results],
      consequences: {
        strong: { target: {}, bystanders: [], sponsor: 20 },
        adequate: { target: {}, bystanders: [], sponsor: 5 },
        weak: { target: {}, bystanders: [], sponsor: -10 },
        harmful: { target: {}, bystanders: [], sponsor: -25 },
      },
    }),
  },
];

export const actions: Actions = { catalogue };
