import type { Events, GameEvent } from "@gk/schema";
import { ACTIONS, STAGES } from "./ids";

const once = { kind: "once" as const };

/** The eight events observed in the Teardown playthrough (weeks 2 to 4), in deck order. */
const observed: GameEvent[] = [
  {
    id: "crm-rollout",
    type: "impact",
    theme: "change",
    trigger: { kind: "fixed", week: 2, day: 1 },
    target: { kind: "role", stageId: STAGES.salesLead },
    delivery: "bulletin",
    title: "New CRM system goes live",
    body: "From this week every lead must be entered in the new CRM. Some of the team are unhappy about the change.",
    impact: { deltas: { morale: -6 } },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "review-site",
    type: "impact",
    theme: "reputation",
    trigger: { kind: "fixed", week: 3, day: 1 },
    target: { kind: "team" },
    delivery: "bulletin",
    title: "Review site criticises our loans",
    body: "Money Matters says Secure Capital Bank's loan features are not innovative. The team has seen it.",
    impact: { deltas: { morale: -3 } },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "kent-personal",
    type: "impact",
    theme: "personal",
    trigger: { kind: "fixed", week: 3, day: 1 },
    target: { kind: "npc", npcId: "kent" },
    delivery: "bulletin",
    title: "Kent's performance drops",
    body: "Kent's results have fallen for personal reasons. If nothing changes he may start blocking other people's leads.",
    impact: { deltas: { morale: -7, result: -10 } },
    expectedResponse: {
      actionIds: [ACTIONS.faceToFace, ACTIONS.reply],
      withinDays: 2,
      reward: { morale: 3, trust: 3 },
    },
    responseWindowDays: 2,
    escalation: { followUpEventId: "kent-blocks-leads" },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "green-leave",
    type: "capacity",
    theme: "personal",
    trigger: { kind: "fixed", week: 3, day: 1 },
    target: { kind: "npc", npcId: "green" },
    delivery: "bulletin",
    title: "Green is on leave this week",
    body: "Green Bell is on casual leave for the whole week.",
    impact: { deltas: {}, capacityLossDays: 5 },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "derick-flu",
    type: "capacity",
    theme: "personal",
    trigger: { kind: "fixed", week: 3, day: 3 },
    target: { kind: "npc", npcId: "derick" },
    delivery: "modal",
    title: "Derick is out sick",
    body: "Derick Kaynes has the flu and is on medical leave for 2 days.",
    impact: { deltas: {}, capacityLossDays: 2 },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "exhaustion-360",
    type: "signal",
    theme: "attrition",
    trigger: { kind: "fixed", week: 4, day: 1 },
    target: { kind: "team" },
    delivery: "bulletin",
    title: "360 degree feedback: the team is exhausted",
    body: "The latest 360 degree feedback says people are tired and need a break.",
    impact: { deltas: {} },
    expectedResponse: {
      actionIds: [ACTIONS.energize, ACTIONS.meetTeam],
      withinDays: 3,
      reward: { morale: 2 },
    },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "lowe-uncongratulated",
    type: "signal",
    theme: "personal",
    trigger: { kind: "fixed", week: 4, day: 1 },
    target: { kind: "npc", npcId: "lowe" },
    delivery: "bulletin",
    title: "Lowe's morale drops",
    body: "Lowe Rex has delivered great results but has never been congratulated.",
    impact: { deltas: { morale: -5 } },
    expectedResponse: {
      actionIds: [ACTIONS.email, ACTIONS.reward],
      withinDays: 3,
      reward: { morale: 4, trust: 3 },
    },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "beth-complaint",
    type: "diagnostic",
    theme: "personal",
    trigger: { kind: "fixed", week: 4, day: 2 },
    target: { kind: "npc", npcId: "beth" },
    delivery: "modal",
    title: "A team member raises a concern about Beth",
    body: "A colleague says your style with Beth needs to change: she needs closer supervision and clearer goals.",
    impact: { deltas: {} },
    repeat: once,
    showImpactLabel: true,
  },
];

/** iLead 2.0 additions: an NPC message and the follow ups that consequences and escalations fire. */
const additions: GameEvent[] = [
  {
    id: "kent-message",
    type: "signal",
    theme: "personal",
    trigger: { kind: "fixed", week: 3, day: 1 },
    target: { kind: "npc", npcId: "kent" },
    delivery: "npc_chat",
    title: "Message from Kent",
    body: "Can we talk? Something has come up at home.",
    impact: { deltas: {} },
    expectedResponse: { actionIds: [ACTIONS.reply, ACTIONS.faceToFace], withinDays: 2, reward: { trust: 3 } },
    responseWindowDays: 5,
    escalation: { followUpEventId: "ceo-complaint" },
    repeat: once,
    showImpactLabel: false,
  },
  {
    id: "kent-blocks-leads",
    type: "impact",
    theme: "personal",
    trigger: { kind: "follow_up" },
    target: { kind: "npc", npcId: "beth" },
    delivery: "bulletin",
    title: "Kent is blocking Beth's leads",
    body: "Kent has started holding back leads that should go to Beth.",
    impact: { deltas: { morale: -3 }, funnelChange: { stageId: STAGES.salesLead, delta: -2 } },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "transfer-request",
    type: "impact",
    theme: "attrition",
    trigger: { kind: "follow_up" },
    target: { kind: "trigger_target" },
    delivery: "modal",
    title: "Transfer request",
    body: "After your last conversation, this team member has asked HR for a transfer.",
    impact: { deltas: { morale: -5 } },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "hr-escalation",
    type: "crisis",
    theme: "compliance",
    trigger: { kind: "follow_up" },
    target: { kind: "team" },
    delivery: "sponsor_call",
    title: "HR escalation",
    body: "HR has received a complaint about how the exit conversation was handled.",
    impact: { deltas: { morale: -3, trust: -5 }, sponsor: -10 },
    repeat: once,
    showImpactLabel: true,
  },
  {
    id: "ceo-complaint",
    type: "crisis",
    theme: "personal",
    trigger: { kind: "follow_up" },
    target: { kind: "sponsor" },
    delivery: "sponsor_call",
    title: "Complaint to the CEO",
    body: "A team member went to Roger Kent after their message went unanswered.",
    impact: { deltas: {}, sponsor: -10 },
    repeat: once,
    showImpactLabel: true,
  },
];

export const events: Events = {
  deck: [...observed, ...additions],
  pacing: { perWeek: [1, 3], intensityCurve: [1, 2, 3, 3, 3, 3, 2, 1] },
};
