import type { Gamification } from "@gk/schema";

/** iLead 2.0 Design gamification layer and docs/scoring-and-report.md section 6. */
export const gamification: Gamification = {
  elements: {
    score: true,
    stars: true,
    streaks: true,
    badges: true,
    sponsorMeter: true,
    unlocks: true,
    teamPulse: true,
    leaderboard: true,
    tiers: true,
  },
  weights: { business: 30, people: 30, leadership: 40 },
  scale: { kind: "0_1000", max: 1000 },
  liveBandScores: { strong: 100, adequate: 70, weak: 35, harmful: 0 },
  stars: [50, 70, 85],
  streak: { minStars: 2, startWeeks: 3, bonusPerWeek: 25, cap: 100 },
  badges: [
    {
      id: "first-close",
      name: "First Close",
      icon: "trophy",
      copy: "Your first conversion landed.",
      lockedHint: "Land your first conversion.",
      event: "conversion",
      condition: "run.conversions >= 1",
      repeatable: false,
      reinforces: "Business focus",
    },
    {
      id: "read-the-room",
      name: "Read the Room",
      icon: "eye",
      copy: "You read almost everyone right this week.",
      lockedHint: "Match the needed style for nearly the whole team in one week.",
      event: "week_end",
      condition: "week.style_fit_pct >= 90",
      repeatable: false,
      reinforces: "Situational flexibility",
    },
    {
      id: "flex-master",
      name: "Flex Master",
      icon: "flex",
      copy: "You used every style correctly at least twice.",
      lockedHint: "Use each style correctly at least twice.",
      event: "week_end",
      condition: "run.min_correct_per_style >= 2",
      repeatable: false,
      reinforces: "Range of styles",
    },
    {
      id: "concern-uncovered",
      name: "Concern Uncovered",
      icon: "search",
      copy: "You surfaced hidden concerns for five people.",
      lockedHint: "Help people share what is really on their mind.",
      event: "interaction_end",
      condition: "run.concerns_surfaced >= min(5, team.size)",
      repeatable: false,
      reinforces: "Listening, coaching",
    },
    {
      id: "promise-keeper",
      name: "Promise Keeper",
      icon: "handshake",
      copy: "You made at least three promises and kept them all.",
      lockedHint: "Make commitments in conversations and keep them.",
      event: "run_end",
      condition: "run.promises_made >= 3 and run.promises_broken == 0",
      repeatable: false,
      reinforces: "Trust and accountability",
    },
    {
      id: "fair-hand",
      name: "Fair Hand",
      icon: "scale",
      copy: "Three recognitions and nobody felt overlooked.",
      lockedHint: "Recognise people fairly.",
      event: "interaction_end",
      condition: "run.recognitions_without_negative_fairness_ripple >= 3",
      repeatable: false,
      reinforces: "Recognition and fairness",
    },
    {
      id: "turnaround",
      name: "Turnaround",
      icon: "rise",
      copy: "You brought someone from low morale to high.",
      lockedHint: "Lift one person's morale from below 30 to above 60.",
      event: "week_end",
      condition: "any_member(morale_was_below_30_then_above_60)",
      repeatable: false,
      reinforces: "Developing people",
    },
    {
      id: "change-champion",
      name: "Change Champion",
      icon: "megaphone",
      copy: "Two strong change conversations.",
      lockedHint: "Communicate change well, twice.",
      event: "interaction_end",
      condition: "run.strong_change_communications >= 2",
      repeatable: false,
      reinforces: "Communicating change",
    },
    {
      id: "steady-hand",
      name: "Steady Hand",
      icon: "shield",
      copy: "Not one harmful moment in the whole run.",
      lockedHint: "Stay professional through every conversation.",
      event: "run_end",
      condition: "run.harmful_bands == 0",
      repeatable: false,
      reinforces: "Professional conduct",
    },
    {
      id: "target-crusher",
      name: "Target Crusher",
      icon: "target",
      copy: "You hit the revenue target.",
      lockedHint: "Reach the revenue target.",
      event: "week_end",
      condition: "run.revenue >= target.value",
      repeatable: false,
      reinforces: "Results ownership",
    },
  ],
  sponsorMeter: {
    start: 50,
    briefing: { strong: 20, adequate: 5, weak: -10, harmful: -25 },
    weekRevenue: { above: 5, below: -5 },
    escalation: -10,
  },
  unlocks: {
    threshold: 70,
    lowThreshold: 30,
    lowPenaltyDays: 1,
    rewards: [
      { id: "bonus-day", kind: "bonus_day", label: "One extra day, once" },
      { id: "hire-budget", kind: "hire_budget", label: "An extra hire budget" },
      { id: "team-activity", kind: "team_activity", label: "A team building slot without cooldown" },
    ],
  },
  tiers: [
    { id: "bronze", name: "Bronze", min: 0 },
    { id: "silver", name: "Silver", min: 500 },
    { id: "gold", name: "Gold", min: 700 },
    { id: "platinum", name: "Platinum", min: 850 },
  ],
  leaderboard: { scope: "cohort", size: 10, anonymous: false, window: "cohort_window" },
  celebrations: "subtle",
};
