import type { Report } from "@gk/schema";
import { ACTIONS, SKILLS, STYLES } from "./ids";

const skill = (
  id: string,
  name: string,
  definition: string,
  strong: string,
  adequate: string,
  weak: string,
  harmful: string,
) => ({
  id,
  name,
  definition,
  bandAnchors: { strong, adequate, weak, harmful },
});

const LEVELS = ["novice", "developing", "proficient", "advanced", "role-model"] as const;
const levelAnchors = (lines: [string, string, string, string, string]) =>
  Object.fromEntries(LEVELS.map((l, i) => [l, lines[i] as string]));

/** iLead 2.0 Design Report 2.0 and docs/scoring-and-report.md sections 5 and 7. */
export const report: Report = {
  sections: [
    { id: "executive_summary", enabled: true },
    { id: "style_flexibility", enabled: true },
    { id: "intent_vs_action", enabled: true },
    { id: "skills_profile", enabled: true },
    { id: "key_moments", enabled: true },
    { id: "people_outcomes", enabled: true },
    { id: "business_outcomes", enabled: true },
    { id: "conversation_analytics", enabled: true },
    { id: "development_plan", enabled: true },
    { id: "methodology", enabled: true },
  ],
  skillsFramework: {
    source: "ilead_default",
    skills: [
      skill(
        SKILLS.flexibility,
        "Situational flexibility",
        "Adapts leadership style to each person's current skill and motivation.",
        "Reads the person's readiness and gives the style they need",
        "Adjusts style in part but misses some cues",
        "Uses the same approach whoever the person is",
        "Ignores the person's state and pushes in a way that harms them",
      ),
      skill(
        SKILLS.coaching,
        "Coaching for growth",
        "Builds capability through good questions, ownership and clear next steps.",
        "Asks questions that help the person find and own a next step",
        "Asks some questions but ends up giving the answer",
        "Tells the person what to do without exploring",
        "Belittles the person's ability",
      ),
      skill(
        SKILLS.feedback,
        "Giving feedback",
        "Gives specific, balanced feedback on the situation, behaviour and impact.",
        "Names the situation, behaviour and impact and agrees what changes",
        "Gives feedback that is fair but vague",
        "Gives general criticism or praise with no example",
        "Attacks the person rather than the behaviour",
      ),
      skill(
        SKILLS.recognition,
        "Recognition and fairness",
        "Recognises contributions specifically and fairly, without favouritism.",
        "Recognises specific contributions and credits everyone who helped",
        "Recognises the person but in general terms",
        "Recognises one person and overlooks others who deserved credit",
        "Plays favourites or humiliates others",
      ),
      skill(
        SKILLS.change,
        "Communicating change",
        "Explains changes clearly, with reasons, and brings people along.",
        "Explains what is changing, why, and what it means for each person",
        "Explains the change but not the reasons",
        "Announces the change with no explanation",
        "Dismisses concerns about the change",
      ),
      skill(
        SKILLS.goals,
        "Goal setting and accountability",
        "Agrees specific, measurable goals and follows up on them.",
        "Agrees specific, measurable goals with the right level of involvement",
        "Sets goals that are clear but not measurable",
        "Sets vague goals or none at all",
        "Sets impossible goals as a threat",
      ),
      skill(
        SKILLS.difficult,
        "Handling difficult conversations",
        "Raises hard topics directly and respectfully, and listens.",
        "Raises the hard topic directly, listens and agrees a way forward",
        "Raises the topic but avoids the hardest part",
        "Avoids the topic or goes straight to targets",
        "Is dismissive, blaming or threatening",
      ),
      skill(
        SKILLS.results,
        "Results ownership",
        "Owns business results honestly and plans credibly to improve them.",
        "Owns the results, names the gaps and presents a credible plan",
        "Owns the results but the plan is thin",
        "Explains results away with excuses",
        "Misleads about the results",
      ),
    ],
  },
  linkage: {
    [SKILLS.flexibility]: [
      ACTIONS.faceToFace,
      ACTIONS.coach,
      ACTIONS.feedback,
      ACTIONS.meetTeam,
      ACTIONS.goals,
      ACTIONS.reply,
    ],
    [SKILLS.coaching]: [ACTIONS.faceToFace, ACTIONS.coach],
    [SKILLS.feedback]: [ACTIONS.feedback, ACTIONS.email, ACTIONS.swap, ACTIONS.fire, ACTIONS.reward],
    [SKILLS.recognition]: [
      ACTIONS.feedback,
      ACTIONS.email,
      ACTIONS.meetTeam,
      ACTIONS.reward,
      ACTIONS.hire,
      ACTIONS.energize,
    ],
    [SKILLS.change]: [ACTIONS.email, ACTIONS.meetTeam, ACTIONS.swap, ACTIONS.fire, ACTIONS.energize],
    [SKILLS.goals]: [ACTIONS.coach, ACTIONS.goals, ACTIONS.briefing],
    [SKILLS.difficult]: [ACTIONS.faceToFace, ACTIONS.feedback, ACTIONS.swap, ACTIONS.fire, ACTIONS.reply],
    [SKILLS.results]: [ACTIONS.goals, ACTIONS.briefing, ACTIONS.hire],
  },
  minObservations: 2,
  ratingScale: [
    { id: "novice", label: "Novice", colour: "#D64545", minScore: 0 },
    { id: "developing", label: "Developing", colour: "#F2A33A", minScore: 40 },
    { id: "proficient", label: "Proficient", colour: "#43D6E8", minScore: 60 },
    { id: "advanced", label: "Advanced", colour: "#1F6FD1", minScore: 75 },
    { id: "role-model", label: "Role Model", colour: "#00A878", minScore: 90 },
  ],
  harmfulCapLevelId: "developing",
  anchors: {
    [SKILLS.flexibility]: levelAnchors([
      "Uses one style for everyone",
      "Changes style sometimes, often too late",
      "Matches the needed style for most people most weeks",
      "Reads changes in people quickly and adjusts",
      "Anticipates what each person will need and adapts before problems appear",
    ]),
    [SKILLS.coaching]: levelAnchors([
      "Gives answers instead of building capability",
      "Asks a few questions, then takes over",
      "Uses questions to help people find their own next step",
      "Builds ownership and follows up on commitments",
      "Grows people so they coach others",
    ]),
    [SKILLS.feedback]: levelAnchors([
      "Rarely gives feedback, or only in general terms",
      "Gives feedback that is fair but vague",
      "Gives specific feedback on behaviour and impact",
      "Balances recognition and challenge and agrees what changes",
      "Creates a team where feedback flows both ways",
    ]),
    [SKILLS.recognition]: levelAnchors([
      "Rarely recognises contributions",
      "Recognises people in general terms",
      "Recognises specific contributions fairly",
      "Spots quiet contributors and shares credit widely",
      "Builds a culture of fair, specific recognition",
    ]),
    [SKILLS.change]: levelAnchors([
      "Announces change without explanation",
      "Explains what is changing but not why",
      "Explains what, why and what it means for people",
      "Anticipates concerns and brings resisters along",
      "Turns change into commitment across the team",
    ]),
    [SKILLS.goals]: levelAnchors([
      "Sets vague goals or none",
      "Sets clear goals that are hard to measure",
      "Agrees specific, measurable goals",
      "Involves people in the right way and follows up",
      "Builds a team that sets and keeps its own goals",
    ]),
    [SKILLS.difficult]: levelAnchors([
      "Avoids hard topics",
      "Raises hard topics but backs away",
      "Raises hard topics directly and respectfully",
      "Listens for the real issue and agrees a way forward",
      "Handles the hardest conversations in a way that builds trust",
    ]),
    [SKILLS.results]: levelAnchors([
      "Explains results away",
      "Owns results but plans are thin",
      "Owns results and presents a credible plan",
      "Names gaps early and adjusts the plan",
      "Owns results in a way that builds the sponsor's confidence",
    ]),
  },
  capabilityBands: { midFrom: 40, highFrom: 70 },
  narrativeBank: [
    {
      id: "overall-novice",
      section: "executive_summary",
      key: { kind: "overall_level", levelId: "novice" },
      text: "You are at the start of building these leadership skills. The priorities below show where to focus first.",
    },
    {
      id: "overall-developing",
      section: "executive_summary",
      key: { kind: "overall_level", levelId: "developing" },
      text: "You showed these skills in some moments but not consistently. Focus on the priorities below to make them habits.",
    },
    {
      id: "overall-proficient",
      section: "executive_summary",
      key: { kind: "overall_level", levelId: "proficient" },
      text: "You led most moments well. The priorities below will take you further.",
    },
    {
      id: "overall-advanced",
      section: "executive_summary",
      key: { kind: "overall_level", levelId: "advanced" },
      text: "You led with skill across most moments, adapting to people and pressure.",
    },
    {
      id: "overall-role-model",
      section: "executive_summary",
      key: { kind: "overall_level", levelId: "role-model" },
      text: "You led at a level others could learn from, across people, change and results.",
    },
    {
      id: "capability-low",
      section: "style_flexibility",
      key: { kind: "capability_band", band: "low" },
      text: "You often used a style that did not match what the person needed. Start by reading each person's skill and morale before you choose.",
    },
    {
      id: "capability-mid",
      section: "style_flexibility",
      key: { kind: "capability_band", band: "mid" },
      text: "You matched the needed style in many moments. Look at the people where you missed most often.",
    },
    {
      id: "capability-high",
      section: "style_flexibility",
      key: { kind: "capability_band", band: "high" },
      text: "You showed high capability in matching your style to each person. Sales could still improve by focusing on the key people in your bottleneck stages.",
    },
    {
      id: "dominant-directing",
      section: "style_flexibility",
      key: { kind: "dominant_style", styleId: STYLES.directing },
      text: "Your most used style was Directing: being direct and giving in-depth instructions.",
    },
    {
      id: "dominant-guiding",
      section: "style_flexibility",
      key: { kind: "dominant_style", styleId: STYLES.guiding },
      text: "Your most used style was Guiding: seeking buy-in from each member to complete the task.",
    },
    {
      id: "dominant-partnering",
      section: "style_flexibility",
      key: { kind: "dominant_style", styleId: STYLES.partnering },
      text: "Your most used style was Partnering: encouraging each member and helping them achieve the task.",
    },
    {
      id: "dominant-entrusting",
      section: "style_flexibility",
      key: { kind: "dominant_style", styleId: STYLES.entrusting },
      text: "Your most used style was Entrusting: delegating with the big picture and monitoring progress.",
    },
    {
      id: "business-line",
      section: "executive_summary",
      key: { kind: "business_line" },
      text: "Revenue reached {revenue} of {target} from {conversions} conversions. Your bottleneck stage was {bottleneck}.",
    },
    {
      id: "not-enough-evidence",
      section: "skills_profile",
      key: { kind: "not_enough_evidence" },
      text: "There was not enough evidence to rate this skill. A rating needs at least two observations from two different conversations.",
    },
  ],
  evidence: { perSkill: 2, redactNames: false },
  developmentPlan: {
    priorities: 3,
    items: [
      {
        skillId: SKILLS.flexibility,
        practiceActivity:
          "Before each one to one this week, write down the person's skill and morale and the style you will use.",
        onTheJobAction: "Change your approach with one person whose needs have shifted.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.coaching,
        practiceActivity: "Run one coaching conversation using goal, reality, options and way forward.",
        onTheJobAction: "Answer a request for help with two questions before you offer advice.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.feedback,
        practiceActivity: "Write three pieces of feedback using situation, behaviour and impact.",
        onTheJobAction: "Give one piece of specific feedback within a day of the moment.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.recognition,
        practiceActivity: "List who contributed to your team's last win, including quiet contributors.",
        onTheJobAction: "Recognise one specific contribution each week, naming everyone who helped.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.change,
        practiceActivity: "Draft a change message that covers what, why and what it means for each person.",
        onTheJobAction: "Hold a short conversation with the person most affected by your next change.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.goals,
        practiceActivity: "Rewrite two of your team's goals so they are specific and measurable.",
        onTheJobAction: "Agree one goal with a team member and book the follow up now.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.difficult,
        practiceActivity: "Plan the opening line of a conversation you have been avoiding.",
        onTheJobAction: "Hold that conversation this week and agree one next step.",
        checkInDays: 30,
      },
      {
        skillId: SKILLS.results,
        practiceActivity: "Prepare a two minute update that names your numbers, gaps and plan.",
        onTheJobAction: "Brief your manager with it before they ask.",
        checkInDays: 30,
      },
    ],
  },
  audiences: ["participant", "ld_admin"],
  delivery: ["in_app", "pdf"],
  branding: "same",
  humanReview: "sample_audit",
  auditSample: { rate: 0.1, minPerInteraction: 5 },
  recognitionPhrases: [
    "thank you",
    "thanks",
    "well done",
    "great work",
    "good job",
    "I appreciate",
    "nice work",
  ],
  methodologyCopy:
    "This is a simulation based development report, not an assessment centre result. Every live conversation was scored against a rubric written for that moment. AI placed each conversation in one of four bands (Strong, Adequate, Weak or Harmful) using that rubric; it never set a score or changed your team's numbers directly. Before publishing, each rubric was checked against labelled examples and had to agree with them at least 85% of the time. A sample of conversations is also reviewed by a trained assessor. A skill is only rated when it was seen in at least two different conversations. Your data is kept for the period your organisation sets. To query a result, contact your programme administrator.",
};
