import type { AreaKey } from "./template";

/**
 * Every setting in the Configuration Spec (205 rows, in document order) mapped to its schema paths.
 * Paths are JSON Pointer patterns; "*" matches any array index or record key.
 * `ai` is true when the Config Spec's "AI generates from context" column drafts a value for the setting.
 */
export interface InventoryRow {
  n: number;
  area: AreaKey;
  setting: string;
  paths: string[];
  ai: boolean;
}

type Row = [n: number, setting: string, paths: string[], ai: boolean];

const npc = (...rest: string[]) => rest.map((r) => `/cast/npcs/*/${r}`);
const action = (...rest: string[]) => rest.map((r) => `/actions/catalogue/*/${r}`);
const ix = (...rest: string[]) => rest.map((r) => `/actions/catalogue/*/interaction/${r}`);
const ev = (...rest: string[]) => rest.map((r) => `/events/deck/*/${r}`);

const rows: Record<AreaKey, Row[]> = {
  context: [
    [1, "Organisation mode", ["/context/organisation/mode"], true],
    [
      2,
      "Organisation name and tagline",
      ["/context/organisation/name", "/context/organisation/tagline"],
      true,
    ],
    [
      3,
      "Industry and sub industry",
      ["/context/organisation/industry", "/context/organisation/subIndustry"],
      true,
    ],
    [
      4,
      "Size, structure, ownership",
      ["/context/organisation/size", "/context/organisation/structure", "/context/organisation/ownership"],
      true,
    ],
    [
      5,
      "Region, city, office type",
      ["/context/organisation/region", "/context/organisation/city", "/context/organisation/officeType"],
      true,
    ],
    [6, "Culture and values", ["/context/organisation/values"], true],
    [7, "Competitors", ["/context/organisation/competitors"], true],
    [
      8,
      "Business situation",
      ["/context/organisation/businessSituation", "/context/organisation/situationNote"],
      true,
    ],
    [9, "Glossary", ["/context/organisation/glossary"], true],
    [10, "Policies NPCs follow", ["/context/organisation/policies"], true],
    [11, "Product lines", ["/context/product/lines"], true],
    [12, "Focus product", ["/context/product/focusLineId"], true],
    [13, "Value proposition and differentiators", ["/context/product/valueProposition"], true],
    [14, "Known weaknesses or criticisms", ["/context/product/weaknesses"], true],
    [15, "Customer segments", ["/context/product/segments"], true],
    [16, "Unit of value", ["/context/product/unitOfValue"], true],
    [17, "Currency and number format", ["/context/product/currency", "/context/product/numberLocale"], true],
    [18, "Participant role title", ["/context/scenario/participantRoleTitle"], true],
    [19, "Level and span", ["/context/scenario/level", "/context/scenario/span"], true],
    [20, "Backstory", ["/context/scenario/backstory"], true],
    [21, "Sponsor persona", ["/context/scenario/sponsorNpcId", "/context/scenario/sponsorStyle"], true],
    [22, "Welcome message", ["/context/scenario/welcomeMessage"], true],
    [23, "Tone of the world", ["/context/scenario/tone"], true],
    [24, "Realism level", ["/context/scenario/realism"], true],
  ],
  branding: [
    [25, "Brand ownership", ["/branding/ownership"], true],
    [26, "Logos", ["/branding/logos"], false],
    [27, "Colour theme", ["/branding/colours"], true],
    [28, "Fonts", ["/branding/fonts"], true],
    [29, "Simulation title and subtitle", ["/branding/title", "/branding/subtitle"], true],
    [30, "Loading and end screen art", ["/branding/loadingArt", "/branding/endArt"], true],
    [31, "Art style", ["/branding/artStyle"], true],
    [32, "Background scenes", ["/branding/backgrounds"], true],
    [33, "Workplace props", ["/branding/props"], true],
    [34, "NPC portraits", ["/branding/portraitDefaultSource", ...npc("look/portrait")], true],
    [35, "Expression set per NPC", ["/branding/expressionSetDefault"], true],
    [36, "Event illustrations", ["/branding/eventIllustrations", ...ev("image")], true],
    [
      37,
      "Icons for actions and stages",
      ["/branding/iconSet", ...action("icon"), "/process/stages/*/icon"],
      true,
    ],
    [38, "Image safety", ["/branding/imageSafety"], false],
    [39, "Sponsor welcome video", ["/branding/media/sponsorWelcomeVideo"], true],
    [40, "Intro and tutorial video", ["/branding/media/introVideo"], true],
    [41, "Ambient sound", ["/branding/media/ambientSound"], true],
    [42, "UI sounds", ["/branding/media/uiSounds"], false],
    [43, "Background music", ["/branding/media/music"], false],
  ],
  cast: [
    [44, "Team size", ["/cast/roster/teamSize"], true],
    [45, "Members per role", ["/cast/roster/membersPerRole"], true],
    [46, "Supporting cast", ["/cast/roster/supportingCast"], true],
    [47, "Archetype mix", ["/cast/roster/archetypeMix", ...npc("profile/archetype")], true],
    [48, "Diversity settings", ["/cast/roster/diversity"], true],
    [49, "Hiring pool", ["/cast/roster/hiringPool", ...npc("candidate")], true],
    [50, "Name, pronouns, age band", npc("identity/name", "identity/pronouns", "identity/ageBand"), true],
    [51, "Portrait source", npc("look/portrait/source"), true],
    [52, "Look", npc("look/attire", "look/setting", "look/accessories"), true],
    [53, "Expression set", npc("look/expressions"), true],
    [54, "Avatar mode", npc("look/avatarMode"), true],
    [55, "Role in team", npc("profile/roleId"), true],
    [56, "Job title", npc("profile/jobTitle"), true],
    [
      57,
      "Previous company, tenure, experience",
      npc("profile/previousCompany", "profile/tenureMonths", "profile/experienceYears"),
      true,
    ],
    [58, "Skills list", npc("profile/skills"), true],
    [59, "Remarks visible to the leader", npc("profile/remarks"), true],
    [60, "Hidden concern", npc("profile/hiddenConcern"), true],
    [61, "Career goal", npc("profile/careerGoal"), true],
    [62, "Starting Skill, Morale, Result", npc("stats/skill", "stats/morale", "stats/result"), true],
    [63, "Starting Trust", npc("stats/trust"), true],
    [64, "Role fit matrix", npc("stats/roleFit"), true],
    [65, "Needed style override", ["/leadership/memberExceptions"], true],
    [66, "Sensitivity weights", npc("stats/sensitivity"), true],
    [67, "Personality sliders", npc("persona/personality"), true],
    [68, "Communication style", npc("persona/communicationStyle"), true],
    [69, "Attitude to the leader at start", npc("persona/attitudeToLeader"), true],
    [70, "Pressure response", npc("persona/pressureResponse"), true],
    [71, "Opening lines and catchphrases", npc("persona/openingLines", "persona/catchphrases"), true],
    [72, "Knowledge scope", npc("persona/knowledgeScope"), true],
    [73, "Off limits topics", npc("persona/offLimitsTopics"), true],
    [74, "Memory depth", npc("persona/memoryDepth"), true],
    [75, "Voice source", npc("voice/source", "voice/voiceId"), true],
    [76, "Language and accent", npc("voice/language", "voice/accent"), true],
    [77, "Pitch, pace, warmth", npc("voice/pitch", "voice/pace", "voice/warmth"), true],
    [78, "Emotional range", npc("voice/emotionalRange", "voice/moodLinked"), true],
    [79, "Pronunciation dictionary", npc("voice/pronunciation"), true],
    [80, "Voice consent record", npc("voice/consentRecordId"), false],
    [81, "Relationship map", ["/cast/relationships"], true],
    [82, "Influence", npc("stats/influence"), true],
    [83, "Ripple rules", ["/cast/rippleRules"], true],
  ],
  process: [
    [84, "Process type", ["/process/type"], true],
    [85, "Number of stages", ["/process/stages"], true],
    [
      86,
      "Stage names, icons, tooltips",
      ["/process/stages/*/name", "/process/stages/*/icon", "/process/stages/*/tooltip"],
      true,
    ],
    [87, "Work unit", ["/process/workUnit"], true],
    [88, "Ideal throughput per stage per week", ["/process/stages/*/idealPerWeek"], true],
    [
      89,
      "Throughput formula weights",
      ["/process/throughput/weights", "/process/throughput/referenceProductivity"],
      true,
    ],
    [90, "Bottleneck rules", ["/process/bottleneck"], false],
    [91, "Parallel or branching stages", ["/process/branching", "/process/stages/*/branchOf"], true],
    [92, "Primary target", ["/process/targets/primary"], true],
    [93, "Value per completed unit", ["/process/targets/valuePerUnit"], true],
    [94, "Secondary targets", ["/process/targets/secondary"], true],
    [95, "Team KPI dials", ["/process/targets/kpiDials"], true],
    [96, "KPI labels", ["/process/targets/kpiLabels"], true],
    [97, "Weekly drift", ["/process/targets/weeklyDrift"], false],
    [98, "Win condition", ["/process/targets/winCondition"], false],
  ],
  leadership: [
    [99, "Framework", ["/leadership/framework"], true],
    [100, "Number of styles", ["/leadership/styles"], false],
    [
      101,
      "Style names and definitions",
      ["/leadership/styles/*/name", "/leadership/styles/*/definition"],
      true,
    ],
    [102, "Readiness bands", ["/leadership/readinessBands"], true],
    [103, "Fit matrix", ["/leadership/fitMatrix"], true],
    [104, "Per member exceptions", ["/leadership/memberExceptions"], true],
    [105, "Role misfit penalty", ["/leadership/roleMisfit"], true],
    [106, "Delta table", ["/leadership/deltaTable"], false],
    [107, "Team feedback messages", ["/leadership/teamFeedback"], true],
    [108, "Style tags for action options", action("options/*/styleTag"), true],
    [109, "Style inference rules for live interactions", ["/leadership/inferenceRules"], true],
    [110, "Intent vs action rule", ["/leadership/intentVsAction"], true],
  ],
  actions: [
    [111, "Name, icon, description", action("name", "icon", "description"), true],
    [112, "Scope", action("scope"), false],
    [113, "Mode", action("mode"), true],
    [114, "Day cost", [...action("dayCost"), ...action("options/*/dayCost")], false],
    [115, "Cooldown", action("cooldownDays"), false],
    [116, "Limits", action("limits"), false],
    [117, "Eligibility rules", action("eligibility"), false],
    [118, "Prerequisites", action("prerequisites"), true],
    [119, "Options (static)", action("options/*/label", "options/*/description"), true],
    [120, "Outcome quotes (static)", action("options/*/quotes"), true],
    [121, "Base consequences", action("baseConsequences", "options/*/consequences", "effects"), true],
    [122, "Unlock condition", action("unlock"), false],
    [123, "Format", ix("format"), false],
    [124, "Input modes allowed", ix("inputModes"), false],
    [125, "Time limit", ix("timeLimit"), false],
    [126, "Turn limit", ix("turnLimit"), false],
    [127, "Participant brief", ix("participantBrief"), true],
    [128, "NPC brief", ix("npcBrief"), true],
    [129, "Difficulty", ix("difficulty"), true],
    [130, "Opening", ix("opening"), false],
    [131, "Rubric dimensions", ix("rubric/dimensions"), true],
    [132, "Concern detection", ix("rubric/concernDetection"), true],
    [133, "Red flags", ix("rubric/redFlags"), true],
    [134, "Outcome bands", ix("bandNames"), false],
    [135, "Consequence table", ix("consequences"), true],
    [136, "Triggers per band", ix("triggers"), true],
    [137, "Hints", ix("hints"), true],
    [138, "Calibration set", ix("calibrationSet"), true],
    [139, "Email specifics", ix("email"), false],
    [140, "Meeting specifics", ix("meeting"), false],
    [141, "Interview specifics", ix("interview"), false],
  ],
  events: [
    [142, "Event type", ev("type"), true],
    [143, "Theme", ev("theme"), true],
    [144, "Trigger", ev("trigger"), true],
    [145, "Probability", ev("trigger/probability"), false],
    [146, "Target", ev("target"), false],
    [147, "Delivery", ev("delivery"), true],
    [148, "Text and image", ev("title", "body", "image"), true],
    [149, "Immediate impact", ev("impact"), false],
    [150, "Expected response", ev("expectedResponse"), true],
    [151, "Response window", ev("responseWindowDays"), true],
    [152, "Escalation chain", ev("escalation"), true],
    [153, "Repeat rules", ev("repeat"), false],
    [154, "Label on card", ev("showImpactLabel"), true],
    [155, "Deck order and pacing", ["/events/deck", "/events/pacing"], true],
  ],
  time: [
    [156, "Play mode", ["/time/playMode"], true],
    [157, "Simulated weeks", ["/time/weeks"], false],
    [158, "Days per week", ["/time/daysPerWeek"], true],
    [159, "Time unit label", ["/time/timeUnitLabel"], false],
    [160, "Live interaction cap", ["/time/liveCap"], false],
    [161, "Real time limit", ["/time/realTimeLimit"], true],
    [162, "Clock pause rules", ["/time/clockPauses"], true],
    [163, "Save and resume", ["/time/saveResume"], true],
    [164, "Sittings", ["/time/sittings"], true],
    [165, "Self paced vs facilitated", ["/time/delivery"], false],
    [166, "Facilitator controls", ["/time/facilitatorControls"], false],
    [167, "Practice week", ["/time/practiceWeek"], false],
  ],
  gamification: [
    [168, "Elements on or off", ["/gamification/elements"], true],
    [169, "Score weights", ["/gamification/weights"], true],
    [170, "Score scale", ["/gamification/scale"], false],
    [171, "Star thresholds", ["/gamification/stars"], false],
    [172, "Streak rules", ["/gamification/streak"], false],
    [173, "Badge library", ["/gamification/badges"], true],
    [174, "Sponsor meter", ["/gamification/sponsorMeter"], false],
    [175, "Unlock rewards", ["/gamification/unlocks"], true],
    [176, "Tier names and thresholds", ["/gamification/tiers"], true],
    [177, "Leaderboard", ["/gamification/leaderboard"], true],
    [178, "Celebrations", ["/gamification/celebrations"], false],
  ],
  report: [
    [179, "Report sections", ["/report/sections"], true],
    [180, "Skills framework", ["/report/skillsFramework"], true],
    [181, "Linkage matrix", ["/report/linkage", "/report/minObservations"], true],
    [182, "Rating scale", ["/report/ratingScale", "/report/harmfulCapLevelId"], false],
    [183, "Behavioural anchors", ["/report/anchors", "/report/skillsFramework/skills/*/bandAnchors"], true],
    [184, "Narrative bank", ["/report/narrativeBank", "/report/capabilityBands"], true],
    [185, "Evidence quotes", ["/report/evidence"], false],
    [186, "Development plan", ["/report/developmentPlan"], true],
    [187, "Audiences", ["/report/audiences"], false],
    [188, "Delivery", ["/report/delivery"], false],
    [189, "Branding", ["/report/branding"], false],
    [190, "Human review tier", ["/report/humanReview", "/report/auditSample"], true],
  ],
  access: [
    [191, "Content languages", ["/access/languages"], true],
    [192, "Mixed language play", ["/access/mixedLanguagePlay"], false],
    [193, "Locale formats", ["/access/localeFormats"], false],
    [194, "Accessibility", ["/access/accessibility"], false],
    [195, "Typed fallback in voice interactions", ["/access/typedFallback"], false],
    [196, "Devices", ["/access/devices"], false],
    [197, "Low bandwidth mode", ["/access/lowBandwidth"], false],
    [198, "Integration", ["/access/integrations"], false],
    [199, "Data and consent", ["/access/dataConsent"], false],
  ],
  governance: [
    [200, "Roles and permissions", ["/governance/roles"], false],
    [201, "Locks", ["/governance/locks"], false],
    [202, "Approval workflow", ["/governance/approval"], false],
    [203, "Versioning", ["/governance/versioning"], false],
    [204, "Templates", ["/governance/templates"], false],
    [205, "Use declaration", ["/governance/useDeclaration"], false],
  ],
};

export const SETTINGS_INVENTORY: readonly InventoryRow[] = (Object.keys(rows) as AreaKey[])
  .flatMap((area) => rows[area].map(([n, setting, paths, ai]) => ({ n, area, setting, paths, ai })))
  .sort((a, b) => a.n - b.n);
