// GENERATED by scripts/tokens/build.ts from tokens/*.json. Do not edit. Run `npm run tokens`.
// Read by the theme loader (src/theme/loader.ts) only, so it stays out of the first load.
import type { ContrastPair, TokenNode } from './paint';

/** Semantic tokens a GenieKreator theme may set (`"themable": true` in tokens/semantic). */
export const THEMABLE = ["color.surface.card","color.surface.solid","color.surface.raised","color.surface.material","color.accent.default","color.accent.secondary","color.accent.soft","fill.brand"] as const;

/** Every WCAG pair the token build checks: the ones declared on semantic tokens and tokens/contrast.json. */
export const PAIRS: ContrastPair[] = [
 {
  "min": 4.5,
  "fg": "color.fg.primary",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.fg.secondary",
  "bg": "color.surface.solid"
 },
 {
  "min": 3,
  "fg": "color.accent.default",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.accent.secondary",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.status.attention",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.status.gain",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.status.decline",
  "bg": "color.surface.solid"
 },
 {
  "min": 4.5,
  "fg": "color.live.replay",
  "bg": "color.surface.solid"
 },
 {
  "fg": "color.fg.primary",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material",
   "color.accent.soft",
   "color.status.attention-soft",
   "color.status.gain-soft",
   "color.status.decline-soft"
  ],
  "min": 4.5,
  "why": "Body text on every surface, selected rows and status chips"
 },
 {
  "fg": "color.fg.secondary",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material"
  ],
  "min": 4.5,
  "why": "Labels and metadata"
 },
 {
  "fg": "color.accent.secondary",
  "bg": [
   "color.surface.card",
   "color.surface.material",
   "color.surface.raised"
  ],
  "min": 4.5,
  "why": "Accent text: eyebrows, Add a reason, Hide, See why, award count, Changed, also on raised rows and chips (D61: Halden's second accent was 4.03:1 there)"
 },
 {
  "fg": "color.live.replay",
  "bg": [
   "color.surface.card",
   "color.surface.raised"
  ],
  "min": 4.5,
  "why": "Replay link under NPC turns"
 },
 {
  "fg": "color.fg.link",
  "bg": [
   "color.surface.solid",
   "color.surface.card",
   "color.surface.material",
   "color.status.attention-soft"
  ],
  "min": 4.5,
  "why": "Ghost buttons, including Continue on the prerequisite nudge"
 },
 {
  "fg": "color.fg.link-hover",
  "bg": [
   "color.surface.solid",
   "color.surface.card",
   "color.surface.material",
   "color.status.attention-soft"
  ],
  "min": 4.5,
  "why": "Ghost buttons on hover"
 },
 {
  "fg": "color.status.attention",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material",
   "color.status.attention-soft"
  ],
  "min": 4.5,
  "why": "12px attention text: Bottleneck this week, urgent inbox label"
 },
 {
  "fg": "color.status.gain",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material",
   "color.status.gain-soft"
  ],
  "min": 4.5,
  "why": "12px gain deltas and chips"
 },
 {
  "fg": "color.status.decline",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material",
   "color.status.decline-soft"
  ],
  "min": 4.5,
  "why": "12px decline deltas and chips"
 },
 {
  "fg": "color.fg.on-accent",
  "bg": "color.accent.default",
  "min": 4.5,
  "why": "Text on accent fills, such as the selected style letter"
 },
 {
  "fg": "button.primary.fg",
  "bg": "button.primary.bg",
  "min": 4.5,
  "why": "Primary button label, at every stop of the brand gradient"
 },
 {
  "fg": "button.secondary.fg",
  "bg": "button.secondary.bg",
  "min": 4.5,
  "why": "Secondary button label"
 },
 {
  "fg": "toast.fg",
  "bg": "toast.bg",
  "min": 4.5,
  "why": "Toast text on its inverted fill"
 },
 {
  "fg": "style.tooltip.fg",
  "bg": "style.tooltip.bg",
  "min": 4.5,
  "why": "Style tooltip text on its inverted fill"
 },
 {
  "fg": "color.accent.secondary",
  "bg": [
   "color.surface.raised"
  ],
  "min": 3,
  "why": "Focus ring (outline-accent-secondary) and selected borders"
 },
 {
  "fg": "color.accent.default",
  "bg": [
   "color.surface.card",
   "color.surface.raised"
  ],
  "min": 3,
  "why": "Bars, selected state"
 },
 {
  "fg": "color.line.control",
  "bg": [
   "color.surface.card",
   "color.surface.raised",
   "color.surface.material"
  ],
  "min": 3,
  "why": "Text fields, composers and choice chips identified by their border"
 },
 {
  "fg": "color.celebration.star",
  "bg": [
   "color.surface.card",
   "color.surface.material"
  ],
  "min": 3,
  "why": "Earned star in the weekly report"
 },
 {
  "fg": "switch.track-off",
  "bg": [
   "color.surface.solid",
   "color.surface.card",
   "color.surface.raised"
  ],
  "min": 3,
  "modes": [
   "light"
  ],
  "why": "Off switch track against its surface. In dark the light thumb carries the boundary (next pair)"
 },
 {
  "fg": "switch.thumb-off",
  "bg": "switch.track-off",
  "min": 3,
  "why": "Off switch thumb against its track"
 },
 {
  "fg": "switch.thumb-on",
  "bg": "switch.track-on",
  "min": 3,
  "why": "On switch thumb against the brand gradient"
 },
 {
  "fg": "color.event.on-tag",
  "bg": "color.event.tag",
  "min": 4.5,
  "over": "fill.event.signal",
  "why": "Event type tag on the lightest event art"
 },
 {
  "fg": "color.event.on-tag",
  "bg": "color.event.tag",
  "min": 4.5,
  "over": "fill.event.opportunity",
  "why": "Event type tag on the opportunity art"
 },
 {
  "fg": "color.event.on-tag",
  "bg": "color.event.tag",
  "min": 4.5,
  "over": "fill.event.crisis",
  "why": "Event type tag on the crisis art"
 },
 {
  "fg": "color.brand.deep-space",
  "bg": [
   "fill.event.impact",
   "fill.event.signal",
   "fill.event.capacity",
   "fill.event.diagnostic",
   "fill.event.opportunity",
   "fill.event.crisis"
  ],
  "min": 3,
  "why": "The event art against the card's dark ink, for the portrait edge"
 },
 {
  "fg": "color.fg.secondary",
  "bg": "color.track",
  "min": 3,
  "why": "Icon of a badge not earned yet, on its empty medal"
 },
 {
  "fg": "color.brand.deep-space",
  "bg": "fill.spectrum",
  "min": 3,
  "why": "Icon of an earned badge on its medal"
 },
 {
  "fg": "color.accent.default",
  "bg": [
   "color.surface.material",
   "color.surface.solid"
  ],
  "min": 3,
  "why": "Border of the incoming sponsor call, the current score marker on the tier scale"
 },
 {
  "fg": "color.report.chart.series",
  "bg": [
   "color.surface.card",
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 3,
  "why": "Report chart, own values: lines, bars, style shares, on the web card, the white print page and the used vs needed grid cells"
 },
 {
  "fg": "color.report.chart.second",
  "bg": [
   "color.surface.card",
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 3,
  "why": "Report chart, second series, dashed: Trust, on the web card, the white print page and the used vs needed grid cells"
 },
 {
  "fg": "color.report.chart.third",
  "bg": [
   "color.surface.card",
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 3,
  "why": "Report chart, third series, dotted: Result, on the web card, the white print page and the used vs needed grid cells"
 },
 {
  "fg": "color.report.chart.reference",
  "bg": [
   "color.surface.card",
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 3,
  "why": "Report chart, targets, ideal markers and axes, on the web card, the white print page and the used vs needed grid cells"
 },
 {
  "fg": "color.report.chart.attention",
  "bg": [
   "color.surface.card",
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 3,
  "why": "Report chart, the hatched bottleneck stage, on the web card, the white print page and the used vs needed grid cells"
 },
 {
  "fg": "color.fg.primary",
  "bg": [
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 4.5,
  "why": "Report chart labels and table text on the print page and in grid cells"
 },
 {
  "fg": "color.fg.secondary",
  "bg": [
   "color.surface.solid",
   "color.report.chart.cell"
  ],
  "min": 4.5,
  "why": "Report chart labels and table text on the print page and in grid cells"
 }
];

/** The tokens those pairs reach, as the build reads them. */
export const NODES: Record<string, TokenNode> = {
 "button.primary.bg": {
  "value": "{fill.brand}"
 },
 "button.primary.fg": {
  "value": "{color.brand.deep-space}"
 },
 "button.secondary.bg": {
  "value": "{color.surface.raised}"
 },
 "button.secondary.fg": {
  "value": "{color.fg.primary}"
 },
 "color.accent.default": {
  "light": "{color.blue.530}",
  "dark": "{color.brand.electric-blue}",
  "themable": true
 },
 "color.accent.secondary": {
  "light": "{color.cyan.520}",
  "dark": "{color.brand.cyber-cyan}",
  "themable": true
 },
 "color.accent.soft": {
  "light": "{color.blue.950}",
  "dark": {
   "ref": "color.blue.620",
   "alpha": 0.18
  },
  "themable": true
 },
 "color.amber.530": {
  "$value": "oklch(0.53 0.13 62)"
 },
 "color.amber.840": {
  "$value": "oklch(0.84 0.14 78)"
 },
 "color.amber.960": {
  "$value": "oklch(0.96 0.04 80)"
 },
 "color.blue.450": {
  "$value": "oklch(0.45 0.17 252)"
 },
 "color.blue.530": {
  "$value": "oklch(0.53 0.17 252)"
 },
 "color.blue.620": {
  "$value": "oklch(0.62 0.17 250)"
 },
 "color.blue.950": {
  "$value": "oklch(0.95 0.03 250)"
 },
 "color.brand.cyber-cyan": {
  "$value": "#43D6E8"
 },
 "color.brand.deep-space": {
  "$value": "#0A081B"
 },
 "color.brand.electric-blue": {
  "$value": "#249DFF"
 },
 "color.brand.mint-green": {
  "$value": "#00F2AD"
 },
 "color.brand.pale-lavender": {
  "$value": "#DEE9FF"
 },
 "color.celebration.star": {
  "light": "{color.cyan.520}",
  "dark": "{color.brand.cyber-cyan}"
 },
 "color.control.track-off": {
  "light": "{color.mist.600}",
  "dark": {
   "ref": "color.white",
   "alpha": 0.12
  }
 },
 "color.coral.530": {
  "$value": "oklch(0.53 0.17 25)"
 },
 "color.coral.780": {
  "$value": "oklch(0.78 0.13 25)"
 },
 "color.coral.960": {
  "$value": "oklch(0.96 0.025 25)"
 },
 "color.cyan.520": {
  "$value": "oklch(0.52 0.12 205)"
 },
 "color.event.lime-100": {
  "$value": "#ECFBC4"
 },
 "color.event.on-tag": {
  "light": "{color.white}",
  "dark": "{color.white}"
 },
 "color.event.rose-100": {
  "$value": "#FFD6CF"
 },
 "color.event.rose-300": {
  "$value": "#F5848C"
 },
 "color.event.tag": {
  "light": {
   "ref": "color.portrait.shade",
   "alpha": 0.8
  },
  "dark": {
   "ref": "color.portrait.shade",
   "alpha": 0.8
  }
 },
 "color.fg.inverse": {
  "light": "{color.white}",
  "dark": "{color.brand.deep-space}"
 },
 "color.fg.link": {
  "light": "{color.blue.530}",
  "dark": "{color.brand.electric-blue}"
 },
 "color.fg.link-hover": {
  "light": "{color.blue.450}",
  "dark": "{color.brand.cyber-cyan}"
 },
 "color.fg.on-accent": {
  "light": "{color.white}",
  "dark": "{color.brand.deep-space}"
 },
 "color.fg.primary": {
  "light": "{color.ink.200}",
  "dark": "{color.lavender.940}"
 },
 "color.fg.secondary": {
  "light": "{color.ink.450}",
  "dark": "{color.lavender.780}"
 },
 "color.ink.200": {
  "$value": "oklch(0.2 0.03 280)"
 },
 "color.ink.450": {
  "$value": "oklch(0.45 0.025 278)"
 },
 "color.lavender.780": {
  "$value": "oklch(0.78 0.03 268)"
 },
 "color.lavender.940": {
  "$value": "oklch(0.94 0.03 265)"
 },
 "color.line.control": {
  "light": "{color.mist.600}",
  "dark": {
   "ref": "color.white",
   "alpha": 0.36
  }
 },
 "color.live.replay": {
  "light": "{color.blue.530}",
  "dark": "{color.brand.cyber-cyan}"
 },
 "color.mint.500": {
  "$value": "oklch(0.5 0.11 165)"
 },
 "color.mint.860": {
  "$value": "oklch(0.86 0.17 165)"
 },
 "color.mint.950": {
  "$value": "oklch(0.95 0.04 165)"
 },
 "color.mist.600": {
  "$value": "oklch(0.6 0.015 270)"
 },
 "color.mist.920": {
  "$value": "oklch(0.92 0.01 270)"
 },
 "color.mist.955": {
  "$value": "oklch(0.955 0.01 270)"
 },
 "color.night.160": {
  "$value": "oklch(0.16 0.035 284)"
 },
 "color.night.170": {
  "$value": "oklch(0.17 0.035 283)"
 },
 "color.portrait.sand-100": {
  "$value": "#FFE7C2"
 },
 "color.portrait.sand-300": {
  "$value": "#F7C17E"
 },
 "color.portrait.shade": {
  "$value": "oklch(0.13 0.03 285)"
 },
 "color.portrait.sky-100": {
  "$value": "#DEE9FF"
 },
 "color.portrait.sky-300": {
  "$value": "#9FDCEB"
 },
 "color.report.chart.attention": {
  "light": "{color.status.attention}",
  "dark": "{color.status.attention}"
 },
 "color.report.chart.cell": {
  "light": "{color.surface.raised}",
  "dark": "{color.surface.raised}"
 },
 "color.report.chart.reference": {
  "light": "{color.fg.secondary}",
  "dark": "{color.fg.secondary}"
 },
 "color.report.chart.second": {
  "light": "{color.accent.secondary}",
  "dark": "{color.accent.secondary}"
 },
 "color.report.chart.series": {
  "light": "{color.accent.default}",
  "dark": "{color.accent.default}"
 },
 "color.report.chart.third": {
  "light": "{color.fg.primary}",
  "dark": "{color.fg.primary}"
 },
 "color.status.attention": {
  "light": "{color.amber.530}",
  "dark": "{color.amber.840}"
 },
 "color.status.attention-soft": {
  "light": "{color.amber.960}",
  "dark": {
   "ref": "color.amber.840",
   "alpha": 0.14
  }
 },
 "color.status.decline": {
  "light": "{color.coral.530}",
  "dark": "{color.coral.780}"
 },
 "color.status.decline-soft": {
  "light": "{color.coral.960}",
  "dark": {
   "ref": "color.coral.780",
   "alpha": 0.14
  }
 },
 "color.status.gain": {
  "light": "{color.mint.500}",
  "dark": "{color.brand.mint-green}"
 },
 "color.status.gain-soft": {
  "light": "{color.mint.950}",
  "dark": {
   "ref": "color.mint.860",
   "alpha": 0.14
  }
 },
 "color.surface.card": {
  "light": "{color.white}",
  "dark": {
   "ref": "color.night.170",
   "alpha": 0.82
  },
  "themable": true
 },
 "color.surface.material": {
  "light": {
   "ref": "color.white",
   "alpha": 0.93
  },
  "dark": {
   "ref": "color.night.160",
   "alpha": 0.93
  },
  "themable": true
 },
 "color.surface.raised": {
  "light": "{color.mist.955}",
  "dark": {
   "ref": "color.white",
   "alpha": 0.06
  },
  "themable": true
 },
 "color.surface.solid": {
  "light": "{color.white}",
  "dark": "{color.night.170}",
  "themable": true
 },
 "color.track": {
  "light": "{color.mist.920}",
  "dark": {
   "ref": "color.white",
   "alpha": 0.1
  }
 },
 "color.white": {
  "$value": "oklch(1 0 0)"
 },
 "fill.brand": {
  "value": "{gradient.brand}",
  "themable": true
 },
 "fill.event.capacity": {
  "value": "linear-gradient(135deg,{color.portrait.sand-100},{color.portrait.sand-300})"
 },
 "fill.event.crisis": {
  "value": "linear-gradient(135deg,{color.event.rose-100},{color.event.rose-300})"
 },
 "fill.event.diagnostic": {
  "value": "linear-gradient(135deg,{color.brand.electric-blue},{color.brand.cyber-cyan})"
 },
 "fill.event.impact": {
  "value": "linear-gradient(135deg,{color.brand.cyber-cyan},{color.brand.mint-green})"
 },
 "fill.event.opportunity": {
  "value": "linear-gradient(135deg,{color.event.lime-100},{color.brand.mint-green})"
 },
 "fill.event.signal": {
  "value": "linear-gradient(135deg,{color.portrait.sky-100},{color.portrait.sky-300})"
 },
 "fill.spectrum": {
  "value": "{gradient.spectrum}"
 },
 "gradient.brand": {
  "$value": "linear-gradient(135deg,#249DFF,#43D6E8)"
 },
 "gradient.spectrum": {
  "$value": "linear-gradient(135deg,#249DFF 0%,#43D6E8 50%,#00F2AD 100%)"
 },
 "style.tooltip.bg": {
  "value": "{color.fg.primary}"
 },
 "style.tooltip.fg": {
  "value": "{color.fg.inverse}"
 },
 "switch.thumb-off": {
  "value": "{color.brand.pale-lavender}"
 },
 "switch.thumb-on": {
  "value": "{color.brand.deep-space}"
 },
 "switch.track-off": {
  "value": "{color.control.track-off}"
 },
 "switch.track-on": {
  "value": "{fill.brand}"
 },
 "toast.bg": {
  "value": "{color.fg.primary}"
 },
 "toast.fg": {
  "value": "{color.fg.inverse}"
 }
};

/** Radius primitives in px, scaled by a theme's radiusScale. */
export const RADII: Record<string, number> = {
 "--il-radius-2": 2,
 "--il-radius-3": 3,
 "--il-radius-4": 4,
 "--il-radius-5": 5,
 "--il-radius-6": 6,
 "--il-radius-8": 8,
 "--il-radius-10": 10,
 "--il-radius-12": 12,
 "--il-radius-14": 14,
 "--il-radius-16": 16,
 "--il-radius-18": 18,
 "--il-radius-20": 20,
 "--il-radius-22": 22,
 "--il-radius-24": 24,
 "--il-radius-26": 26,
 "--il-radius-28": 28,
 "--il-radius-30": 30,
 "--il-radius-32": 32
};
